try

diff --git a/.github/workflows/ngrok-deploy.yml b/.github/workflows/ngrok-deploy.yml
--- a/.github/workflows/ngrok-deploy.yml
+++ b/.github/workflows/ngrok-deploy.yml
@@ -11,7 +11,12 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v2
+
+      - name: Install Dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y docker-compose jq curl
 
       - name: Download and Install Ngrok
         run: |
@@ -19,6 +24,27 @@ jobs:
           unzip ngrok-stable-linux-amd64.zip
           sudo mv ngrok /usr/local/bin/
           ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}
+
+      - name: Start Backend with Docker Compose
+        uses: docker/compose-action@v2.0.0
+        with:
+          compose-file: "./docker-compose.yml"
+          up-flags: "--build -d backend"
+
+      - name: Wait for Backend to Start
+        run: |
+          echo "Waiting for backend to be accessible on port 5000..."
+          RETRIES=10
+          until curl -s http://localhost:5000 > /dev/null; do
+            echo "Backend not available yet. Retrying..."
+            RETRIES=$((RETRIES-1))
+            if [ $RETRIES -le 0 ]; then
+              echo "Error: Backend did not become available in time."
+              exit 1
+            fi
+            sleep 5
+          done
+          echo "Backend is up and running on port 5000."
 
       - name: Start Ngrok for localhost:5000
         run: |
@@ -30,14 +56,6 @@ jobs:
           NGROK_URL=$(curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
           echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_ENV
           echo "Fetched Ngrok URL: $NGROK_URL"
-
-      - name: Run Docker Compose
-        uses: hoverkraft-tech/compose-action@v2.0.1
-        with:
-          compose-file: "./docker-compose.yml"
-          up-flags: "--build -d"
-        env:
-          REACT_APP_BACKEND_URL: ${{ env.NGROK_URL }}
 
       - name: Update Env Var in Frontend's .env file
         run: |
